### ISSUE TITLE
List of important Nyanotrasen/Delta-V features to copy over

### ISSUE THREAD

**Issue by ps3moira** [greystation14/GreyStation14#4]
# Description
## High priority
- [ ] HoS Gun (Delta)
- [ ] Captain's Spare ID (Delta)
- [ ] UPDATE SPRITES
## Medium priority
- [ ] Glimmer (Delta)
- [ ] Midround antags (Delta/Nyano)
- [ ] Deep fryer (Delta)
- [ ] Mail (Delta)
## Low priority
- [ ] BB Gun (Delta)
- [ ] Scottish Trait (Delta)
- [ ] Mouse Ops (Delta)
- [ ] Sounds Effects (Parkstation)
- [ ] Drones (Nyano)

TODO

**Comment by JoeHammad1844** [comment]
#43
#29
